"""empty message

Revision ID: 3753bb497fc9
Revises: 94ebc8d70e14
Create Date: 2019-07-25 16:34:46.827725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3753bb497fc9'
down_revision = '94ebc8d70e14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parcel_name', sa.String(length=100), nullable=True),
    sa.Column('parcel_number', sa.String(length=100), nullable=True),
    sa.Column('pickup_destination', sa.String(length=100), nullable=True),
    sa.Column('delivery_destination', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parcel_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parcels')
    # ### end Alembic commands ###
