"""empty message

Revision ID: 977aacf533bb
Revises: 90f79c1e9d89
Create Date: 2019-07-30 14:37:44.899661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '977aacf533bb'
down_revision = '90f79c1e9d89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'parcel_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('parcel_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
